export const en = {
  translation: {
    manageVideoCategories: 'Manage Video Categories',
    inputVideoCategory: 'Input Video Category',
    addNew: 'Add New',
    inputVideoCatName: 'Category cannot be empty',
    catCannotBeDuplicated: 'Category cannot be duplicated',
    addNewVideo: 'Add New Video',
    submitData: 'Submit Data',
    videoUrl: 'Video URL',
    invalidUrl: 'Invalid url format',
    videoTitle: 'Video Title',
    inputVideoTitle: 'Input Video Title',
    videoCategory: 'Video Category',
    videoDescription: 'Video Description',
    inputVideoDescription: 'Input Video Description',
    confirmDeleteVideo: 'Do you ensure to delete the video?',
    shareLink: 'Share Link',
    confirm: 'Confirm',
    cancel: 'Cancel',
    searchVideo: 'Search Video',
    noCategory: 'None',
    videoList: 'Video List',
    video: 'Video',
    category: 'Category',
    manageTimestamp: 'Manage Timestamp Categories',
    inputTimestampCategory: 'Category cannot be empty',
    tsCatCannotBeDuplicated: 'Category cannot be duplicated',
    timestamp: 'Timestamp',
    searchTimestamp: 'Search Timestamp',
    startTime: 'Start',
    endTime: 'End',
    currentTime: 'Current',
    addNewTimestamp: 'Add new Timestamp',
    timestampName: 'Name',
    timestampCategory: 'Timestamp Category',
    optionalDescription: 'Description (optional)',
    noDescription: 'No description',
    save: 'Save',
  },
};
